apiVersion: v1
kind: Service
metadata:
  name: my-service-dev
  namespace: dev-ns
  labels:
    app: my-service
    environment: dev
spec:
  type: ClusterIP
  replicas: 1
  clusterIP: dev-cluster.internal
