image:
  repository: ghcr.io/myorg/my-service
  tag: v1.2.3

replicaCount: 2

env:
  - name: DATABASE_URL
    value: 'uat-database.postgres.internal'
  - name: CACHE_URL
    value: 'redis.uat.internal'
  - name: LOG_LEVEL
    value: 'info'

service:
  name: my-service-uat
  port: 8080

resources:
  requests:
    memory: '256Mi'
    cpu: '200m'
