image:
  repository: ghcr.io/myorg/my-service
  tag: v1.2.3

replicaCount: 1

env:
  - name: DATABASE_URL
    value: 'dev-database.postgres.internal'
  - name: CACHE_URL
    value: 'redis.dev.internal'
  - name: LOG_LEVEL
    value: 'debug'

service:
  name: my-service-dev
  port: 8080

resources:
  requests:
    memory: '128Mi'
    cpu: '100m'
